version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_HOST=%
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/product_images:/usr/src/app/product_images
    working_dir: /usr/src/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ecommerce
    command: npx nodemon server.js

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  db_data:
