version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    image: europe-west1-docker.pkg.dev/zinc-mantra-460321-t3/repo/backend:latest
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Prevent node_modules overwriting
    working_dir: /usr/src/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ecommerce
      SESSION_SECRET: secret123 # Optional but useful
    command: npx nodemon server.js

  backend-test:
    build: ./backend
    container_name: backend_test_container
    restart: "no" # Important: no infinite restart after test ends
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ecommerce
      NODE_ENV: test
      SESSION_SECRET: testsecret # Prevent session errors
    entrypoint: ["npm", "run", "test"]

  frontend:
    build: ./frontend
    image: europe-west1-docker.pkg.dev/zinc-mantra-460321-t3/repo/frontend:latest
    container_name: frontend_container
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  db_data: